#!/bin/sh

uci set luci.main.lang='en'
uci commit luci
#timezone
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system
#ssrp
sed -i 's/local ucic = uci.cursor()/local ucic = luci.model.uci.cursor()/g' /usr/share/shadowsocksr/subscribe.lua
sed -i "s/'cbid.shadowsocksr.'/'widget.cbid.shadowsocksr.'/g" /usr/lib/lua/luci/view/shadowsocksr/ssrurl.htm
#feed
sed -i '/openwrt_packages/ { s/snapshots\/packages/releases\/packages-19.07/g; }' /etc/opkg/distfeeds.conf
sed -i '/openwrt_routing/ { s/snapshots\/packages/releases\/packages-19.07/g; }' /etc/opkg/distfeeds.conf
sed -i '/openwrt_telephony/ { s/snapshots\/packages/releases\/packages-19.07/g; }' /etc/opkg/distfeeds.conf
sed -i '/natelol/d' /etc/opkg/distfeeds.conf
sed -i 's,downloads.openwrt.org,mirrors.cloud.tencent.com/lede,g' /etc/opkg/distfeeds.conf
#uhttpd
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci commit uhttpd
/etc/init.d/uhttpd restart
#network
#uci set network.globals.packet_steering=1
#uci commit network
#/etc/init.d/network restart
#firewall
uci set firewall.@zone[1].fullcone='1'
uci commit firewall
#SSL
sed -i 's,#devcrypto,devcrypto,g' /etc/ssl/openssl.cnf
sed -i 's,#USE_SOFTDRIVERS = 2,USE_SOFTDRIVERS = 1,g' /etc/ssl/openssl.cnf
#chinalist
#dnsmasq
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf
ln -sf /sbin/ip /usr/bin/ip
opkg flag hold luci-app-firewall
opkg flag hold firewall
opkg flag hold dnsmasq-full
#sync; echo 3 > /proc/sys/vm/drop_caches
#luci cache
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache
exit 0
